In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

A bank found that the average number of cars waiting during the noon hour at a drive-up window follows a Poisson distribution with a mean of 2 cars. Make a chart of this distribution and answer these questions concerning the probability of cars waiting at the drive-up window.

- What is the probability that no cars drive up in the noon hour?

In [2]:
stats.poisson(2).pmf(0)

0.1353352832366127

In [33]:
(np.random.poisson(2, 100000) == 0).mean()

0.13448

- What is the probability that 3 or more cars come through the drive through?

In [3]:
stats.poisson(2).sf(2)

0.32332358381693654

In [34]:
(np.random.poisson(2, 100000) >= 3).mean()

0.32342

- How likely is it that the drive through gets at least 1 car?

In [36]:
stats.poisson(2).sf(0)

0.8646647167633873

In [37]:
(np.random.poisson(2, 100000) >= 1).mean()

0.86515

Grades of State University graduates are normally distributed with a mean of 3.0 and a standard deviation of .3. Calculate the following:

- What grade point average is required to be in the top 5% of the graduating class?

In [9]:
stats.norm(3, .3).isf(.05)

3.4934560880854417

In [10]:
stats.norm(3, .3).isf(.05) == stats.norm(3, .3).ppf(.95)

True

In [58]:
np.quantile(np.random.normal(3, .3, 10000), .95)

3.5016378888844493

- What GPA constitutes the bottom 15% of the class?

In [59]:
np.quantile(np.random.normal(3, .3, 10000), .15)

2.695663448481629

In [12]:
stats.norm(3, .3).ppf(.15)

2.689069983151863

- An eccentric alumnus left scholarship money for students in the third decile from the bottom of their class. Determine the range of the third decile. Would a student with a 2.8 grade point average qualify for this scholarship?

Decile: 10s

1. First Decile: 0-10 percentile
2. Second Decile: 10-20 percentile
3. Third Decile: 20-30 percentile

In [13]:
stats.norm(3, .3).ppf([.2, .3,])

array([2.74751363, 2.84267985])

In [60]:
np.quantile(np.random.normal(3, .3, 10000), [.2, .3])

array([2.74794973, 2.84421826])

- If I have a GPA of 3.5, what percentile am I in?

In [14]:
stats.norm(3, .3).cdf(3.5)

0.9522096477271853

In [62]:
1 - (np.random.normal(3, .3, 10000) >= 3.5).mean()

0.952

A marketing website has an average click-through rate of 2%. One day they observe 4326 visitors and 97 click-throughs. How likely is it that this many people or more click through?

In [63]:
p = .02
n = 4326

stats.binom(n, p).sf(96)

0.1397582363130086

In [72]:
(np.random.choice([1, 0], p=[.02, .98], size=(10000, 4326)).sum(axis=1) >= 97).mean()

0.1336

You are working on some statistics homework consisting of 100 questions where all of the answers are a probability rounded to the hundreths place. Looking to save time, you put down random probabilities as the answer to each question.

What is the probability that at least one of your first 60 answers is correct?

In [73]:
p = .01
n = 60

stats.binom(n, p).sf(0)

0.4528433576092388

In [85]:
(np.random.uniform(size=(1000, 60)).round(2) == np.random.uniform(size=(1000, 60)).round(2)).any(axis=1).mean()

0.444

The codeup staff tends to get upset when the student break area is not cleaned up. Suppose that there's a 3% chance that any one student cleans the break area when they visit it, and, on any given day, about 90% of the 3 active cohorts of 22 students visit the break area. How likely is it that the break area gets cleaned up each day? How likely is it that it goes two days without getting cleaned up? All week?

In [93]:
p = .03
n = round(.9 * 3 * 22)

stats.binom(n, p).sf(0)

0.8342199288437355

In [96]:
(np.random.choice([1, 0], p=[.03, .97], size=(1000, n)).sum(axis=1) > 0).mean()

0.832

2 days without getting cleaned up

In [97]:
1 - stats.binom(n * 2, p).sf(0)

0.02748303199257618

In [101]:
(np.random.choice([1, 0], p=[.03, .97], size=(1000, n * 2)).sum(axis=1) == 0).mean()

0.03

All week without being cleaned up

In [110]:
p = .03
n = round(.9 * 3 * 22)

1 - stats.binom(n * 5, p).sf(0)

0.00012521651388086585

In [109]:
(np.random.choice([1, 0], p=[.03, .97], size=(10000, n * 5)).sum(axis=1) == 0).mean()

0.0002

You want to get lunch at La Panaderia, but notice that the line is usually very long at lunchtime. After several weeks of careful observation, you notice that the average number of people in line when your lunch break starts is normally distributed with a mean of 15 and standard deviation of 3. If it takes 2 minutes for each person to order, and 10 minutes from ordering to getting your food, what is the likelihood that you have at least 15 minutes left to eat your food before you have to go back to class? Assume you have one hour for lunch, and ignore travel time to and from La Panaderia.

In [111]:
# Let's use minutes for the units here, because that's ultimately what we need
mean = 15 * 2 # people times minutes to order
sd = 3 * 2 # people times minutes to order

time_for_lunch = 60
time_to_get_food = 10
time_to_eat = 15

# maximum amount of time we can wait in line
wait_time_cap = time_for_lunch - (time_to_get_food + time_to_eat)

stats.norm(mean, sd).cdf(wait_time_cap)

0.7976716190363569

In [112]:
(np.random.normal(mean, sd, 10000) <= wait_time_cap).mean()

0.7924

Connect to the employees database and find the average salary of current employees, along with the standard deviation. For the following questions, calculate the answer based on modeling the employees salaries with a normal distribution defined by the calculated mean and standard deviation then compare this answer to the actual values present in the salaries dataset.

In [119]:
import env

url = f'mysql+pymysql://{env.user}:{env.password}@{env.host}/employees'
query = '''
SELECT *
FROM salaries s
WHERE emp_no IN (
    SELECT emp_no FROM dept_emp
    WHERE to_date > NOW()
) AND to_date > NOW()
'''
    
salaries = pd.read_sql(query, url)

In [121]:
mean = salaries.salary.mean()
sd = salaries.salary.std()

- What percent of employees earn less than 60,000?

In [122]:
stats.norm(mean, sd).cdf(60000)

0.24385742480214423

In [123]:
(salaries.salary < 60000).mean()

0.2705727041028802

- What percent of employees earn more than 95,000?

In [124]:
(salaries.salary > 95000).mean()

0.1086272092752078

In [125]:
stats.norm(mean, sd).sf(95000)

0.09208819199804053

- What percent of employees earn between 65,000 and 80,000?

In [133]:
((salaries.salary >= 65000) & (salaries.salary <= 80000)).mean()

0.32515700221552196

In [132]:
np.diff(stats.norm(mean, sd).cdf([65000, 80000]))

array([0.33506057])

- What do the top 5% of employees make?

In [135]:
salaries.salary.quantile(.95)

104225.84999999998

In [136]:
stats.norm(mean, sd).isf(.05)

100484.64454102777